export const MUSIC_GENRES = [
  "Folk",
  "R&B",
  "Blues",
  "Country",
  "Reggae",
  "Jazz",
  "Classical",
  "Electronic",
  "Hip-Hop/Rap",
  "Rock",
  "Pop",
  "Soundtrack",
  "World",
  "Indie",
  "Dance",
  "Gospel",
  "K-Pop",
  "Latin",
  "Alternative",
  "Disco",
  "Metal",
  "Soul",
]

export const MUSIC_MOODS = [
  { id: "celebratory", name: "احتفالي", color: "bg-yellow-100 text-yellow-800" },
  { id: "relaxing", name: "مريح", color: "bg-blue-100 text-blue-800" },
  { id: "strong", name: "قوي", color: "bg-red-100 text-red-800" },
  { id: "emotional", name: "عاطفي", color: "bg-purple-100 text-purple-800" },
  { id: "feminine", name: "نسائي", color: "bg-pink-100 text-pink-800" },
  { id: "dancing", name: "راقص", color: "bg-orange-100 text-orange-800" },
  { id: "romantic", name: "رومانسي", color: "bg-green-100 text-green-800" },
  { id: "calm", name: "هادئ", color: "bg-gray-100 text-gray-800" },
  { id: "enthusiastic", name: "حماسي", color: "bg-indigo-100 text-indigo-800" },
  { id: "desired", name: "مريد", color: "bg-teal-100 text-teal-800" },
  { id: "sad", name: "حزين", color: "bg-slate-100 text-slate-800" },
]
